name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4.1.9
